[package]
name = "mirror-delay"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "*", default-features = false, features = ["serde"] }
psl = "*"
rand = "*"
rand_distr = "*"
reqwest = { version = "*", features = ["json", "blocking", "native-tls", "native-tls-alpn"], default-features = false }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
url = { version = "*", features = ["serde"] }
