[package]
name = "mirror-delay"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "*", default-features = false, features = ["serde"] }
eyre = "*"
futures = "*"
httpdate = "*"
psl = "*"
rand = "*"
rand_distr = "*"
# can't use http2 here: https://github.com/seanmonstar/reqwest/issues/2204
reqwest = { version = "*", features = ["json", "native-tls"], default-features = false }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sqlx = { version = "*", default-features = false, features = ["postgres", "runtime-tokio"] }
tokio = { version = "*", features = ["rt", "time", "net"] }
url = { version = "*", features = ["serde"] }
