#!/usr/bin/env python3

import datetime
import os

from github import GitHub

def main():
  token = os.environ['GITHUB_TOKEN']
  gh = GitHub(token)
  repo = 'archlinuxcn/repo'
  now = datetime.datetime.now(datetime.timezone.utc)
  waiting_time = datetime.timedelta(days=30)

  for issue in gh.get_repo_issues(repo, labels='package-request'):
    if now - issue.updated_at > waiting_time:
      print(f'Marking {issue} as failed')
      issue.comment('''\
请求太久无回应，关闭。

This request has been waiting for too long, closing.''')
      issue.add_labels(['request-failed'])
      issue.close()

if __name__ == '__main__':
  main()
