#!/bin/bash -e

if [ "x$1" = "xbuild" ]; then
  pkgdir="/home/repo"
  host="repopull@build.archlinuxcn.org"
else
  echo "no such configuration." >&2
  exit 1
fi

dstdir="/data/archlinuxcn/repo/data"
workdir="$dstdir.work"

date=$(ssh "$host" date "+%s")
for arch in any i686 x86_64 arm armv6h armv7h aarch64; do
  mkdir -p "$workdir/$arch"
  rsync -virtO --partial --bwlimit 10000 --exclude='Put *' --include="*-${arch}.pkg.tar.*" --exclude='*' $host:$pkgdir/ $workdir/$arch
  mv $workdir/$arch/* $dstdir/$arch/
done

# shellcheck disable=SC2029
ssh "$host" /srv/removepkg "\"I'm sure\"'!'" "$date"
