#!/bin/bash -e

rsync -rtlivH --delete-after --delay-updates --safe-links --max-delete=1000 --contimeout=60 --include='/pool/' --include='/pool/**' --exclude='*' mirror.pkgbuild.com::packages/ /data/archlinux
