#!/usr/bin/python3

import json
import time

import requests
import progressbar

def main():
  s = requests.Session()

  url = 'https://pkgstats.archlinux.de/api/packages'
  params = {
    'offset': '0',
    'limit': '10000',
  }

  offset = 0
  bar = progressbar.ProgressBar(max_value=1)
  bar.update(0)

  r = s.get(url, params=params)
  data = r.json()

  total = data['total']
  offset += data['count']
  pkgdata = data['packagePopularities']

  bar.max_value = total
  bar.update(offset)
  progressbar.streams.flush()

  while offset < total:
    time.sleep(1)
    params['offset'] = str(offset)
    r = s.get(url, params=params)
    data = r.json()
    pkgdata += data['packagePopularities']
    offset += data['count']
    bar.update(offset)

  print()

  with open('pkgstats.json', 'w') as f:
    json.dump(pkgdata, f)

if __name__ == '__main__':
  try:
    main()
  except IndexError:
    main()
