#!/bin/bash -e

cd /usr/share/webapps/mediawiki

patch -p0 <<'EOF'
--- Sanitizer.php	2023-01-10 14:50:23.056232819 +0800
+++ Sanitizer.php	2023-01-10 14:50:43.652403140 +0800
@@ -191,7 +191,7 @@
 			$htmlnest = [ # Tags that can be nested--??
 				'table', 'tr', 'td', 'th', 'div', 'blockquote', 'ol', 'ul',
 				'li', 'dl', 'dt', 'dd', 'font', 'big', 'small', 'sub', 'sup', 'span',
-				'var', 'kbd', 'samp', 'em', 'strong', 'q', 'ruby', 'bdo'
+				'var', 'kbd', 'samp', 'em', 'strong', 'q', 'ruby', 'bdo', 'aside'
 			];
 			$tabletags = [ # Can only appear inside table, we will close them
 				'td', 'th', 'tr',
EOF
