#!/usr/bin/python3

from __future__ import annotations

import json
import asyncio
from collections import defaultdict

import const
from agithub import GitHub

async def main() -> None:
  gh = GitHub(const.GITHUB_TOEKN)
  comments = [c async for c in gh.get_issue_comments(
    'archlinuxcn/repo', const.ISSUE_NR)
  ]
  removed = defaultdict(list)
  waiting_user = []

  for comment in comments:
    lines = comment.body.splitlines()
    it = iter(lines)
    l = next(it)
    if not l.startswith('@'):
      continue
    # strict checking for initiator
    if comment.author == 'lilydjwg' and not l.endswith(':'):
      continue

    who = l[1:].rstrip(':')
    # wrong @
    if who == 'lilydjwg' and comment.author != 'lilydjwg':
      who = comment.author
    if comment.author not in [who, 'lilydjwg']:
      continue

    all_unchecked = True
    for l in it:
      if not l.strip():
        continue
      # alternative list marker
      if l.startswith('- '):
        l = '* ' + l[2:]
      if not l.startswith('* ['):
        break
      checked = l.lower().startswith('* [x] ')
      name = l.split(']', 1)[1].split(None, 1)[0]
      # print(who, name, checked)
      if not checked:
        removed[who].append(name)
      else:
        all_unchecked = False
        try:
          removed[who].remove(name)
        except ValueError:
          pass

    if all_unchecked:
      waiting_user.append(who)
    else:
      try:
        waiting_user.remove(who)
      except ValueError:
        pass

  with open('/home/lilydjwg/tmpfs/removed.json', 'w') as f:
    json.dump({'removed': removed, 'waiting_user': waiting_user}, f)

if __name__ == '__main__':
  asyncio.run(main())
