[package]
name = "cleanup-package-files"
version = "0.1.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

[dependencies]
nix = "*"
eyre = "*"
expanduser = "*"
pwd = "*"

[dependencies.structopt]
version = "*"
default-features = false
features = []

[profile.release]
lto = true
